// ============================================================
// SAMPLE — bubble holographic portfolio · 5 projects
// ============================================================
window.SAMPLE_BUBBLE = {
  kor: {
    badge: 'Portfolio · 2026',
    status: 'available · q3',
    name: ['Park', 'Junghyeok'],
    lang: { kor: '한국어', en: 'English' },
    role: '독립 프로덕트 디자이너. 금융과 도구, 그리고 조용한 인터페이스에 관심이 있습니다. 작은 팀과 끝까지 만드는 일을 좋아합니다.',
    heroMeta: ['Seoul · KST', 'Est. 2017', '47 shipped', 'booking q3'],
    sectionLabel: '작품',
    sectionMeta: '01 — 05 · 2023 → 2025',
    autoLabel: '흐르는 중',
    pausedLabel: '잠시 멈춤',
    nudge: '카드 위에 마우스를 올리면 흐름이 멈춥니다. 클릭하면 상세로.',
    nudgeReduced: '← → 화살표로 직접 넘기세요.',
    actions: { back: '목록으로', visit: '사이트 방문', prev: '이전', next: '다음' },
    arrow: { l: '←', r: '→' },
    detail: {
      year: 'YEAR', role: 'ROLE', client: 'CLIENT',
      did: '한 일',
      outcome: '결과',
      tags: '태그',
      ofTotal: (i, n) => `${String(i).padStart(2,'0')} / ${String(n).padStart(2,'0')}`,
      keyboardHint: '← → 키로 이동 · Esc로 닫기',
    },
    footer: {
      l: '© Park Junghyeok · 2026',
      c: 'Set in Fredoka + Gowun Dodum · made with care',
      email: 'hello@junghyeok.kr',
      github: 'github.com/junghyeok',
    },
    toast: { lang: '언어 변경 · 한국어' },
    projects: [
      {
        id: 'calm-banking', num: '01', y: '2025',
        category: 'company', categoryLabel: '회사',
        client: 'Lattice Bank',
        title: 'Calm Banking',
        tagline: '복잡한 송금 흐름을 한 화면으로 단정하게 줄였습니다.',
        tags: ['Mobile', 'Fintech', 'Lead'],
        thumbGrad: 'linear-gradient(135deg, #FFD3E2 0%, #FFE5C2 35%, #C8F0E1 70%, #C8DBFF 100%)',
        thumbAccent: '#FF7FAE',
        thumbLabel: 'Transfer Flow · v.02',
        role: 'Lead Product Designer · 7개월', roleSub: 'iOS · Android',
        did: [
          '거래 흐름 5단계를 3단계로 축약, 잘못 보낸 송금 되돌리기 패턴 신규 도입',
          '계좌·카드 정보를 단일 카드 UI로 재설계, 모듈 32개를 12개로 정리',
          '온보딩 5개 화면 신규 — 첫 송금까지 평균 시간 측정 가능하게 함',
        ],
        outcome: [
          ['−38%', 'D7 신규 이탈률'],
          ['22→9s', '평균 송금 완료'],
          ['4.8★', 'App Store · 12.4k'],
        ],
        live: true,
      },
      {
        id: 'foundry-docs', num: '02', y: '2024',
        category: 'personal', categoryLabel: '개인',
        client: 'Open Source',
        title: 'Foundry Docs',
        tagline: '개발자 문서를 잡지처럼 읽히게 만든 정적 사이트 키트.',
        tags: ['Web', 'Tooling'],
        thumbGrad: 'linear-gradient(135deg, #D9F4E5 0%, #CFE9FF 35%, #E2D3FF 70%, #FFD7F0 100%)',
        thumbAccent: '#8EC8B2',
        thumbLabel: 'Docs · /api/v2',
        role: 'Solo · Design & Build', roleSub: '12주',
        did: [
          '5단계 정보 위계를 책의 본문·각주·여백 모델로 재해석',
          '코드 블록과 본문을 한 그리드 안에서 정렬되도록 12-column 시스템 설계',
          '검색·내비게이션·다크모드 전환을 단축키 한 손으로 가능하게 함',
        ],
        outcome: [
          ['2.1k', 'GitHub stars'],
          ['14', 'OSS 채택'],
          ['4m 12s', '평균 체류'],
        ],
      },
      {
        id: 'saebyul-reader', num: '03', y: '2024',
        category: 'student', categoryLabel: '졸업작품',
        client: 'SNU Visual Design',
        title: 'Saebyul Reader',
        tagline: '한국 단편소설을 위한 새벽 시간대 독서 앱.',
        tags: ['Mobile', 'Reading'],
        thumbGrad: 'linear-gradient(135deg, #E5D5FF 0%, #FFD5EC 35%, #FFE3D5 70%, #FFF1C8 100%)',
        thumbAccent: '#B89BE0',
        thumbLabel: 'Read · 03:14 AM',
        role: 'Solo · UX/UI', roleSub: '졸업 프로젝트 · 16주',
        did: [
          '한글 본문 조판 — 글자 사이·행간·여백을 시간대 따라 자동 조정',
          '한 호흡 단위로 끊어주는 문장 페이서 인터랙션 신규 설계',
          '오프라인 우선 아키텍처와 작가별 컬렉션 UI 구성',
        ],
        outcome: [
          ['27분', '평균 세션'],
          ['64%', '재방문율'],
          ['SDF', '신인상 본선'],
        ],
      },
      {
        id: 'studio-kettle', num: '04', y: '2023',
        category: 'client', categoryLabel: '클라이언트',
        client: 'Local Brewery',
        title: 'Studio Kettle',
        tagline: '동네 양조장의 시즌별 라벨과 예약 사이트.',
        tags: ['Brand', 'Web'],
        thumbGrad: 'linear-gradient(135deg, #FFE9C2 0%, #FFD3D3 35%, #FFD3EC 70%, #E2D3FF 100%)',
        thumbAccent: '#F0A878',
        thumbLabel: 'Brew · SS_23',
        role: 'Lead Designer · 8주', roleSub: '브랜드 + 웹',
        did: [
          '시즌마다 바뀌는 라벨 시스템을 단일 그리드 위에서 모듈식으로 구성',
          '주중 한정 메뉴 예약 흐름을 3-step으로 단순화',
          '사진 없이도 메뉴를 묘사할 수 있는 타이포 중심 카드 시스템',
        ],
        outcome: [
          ['8주', '연속 예약 만석'],
          ['600→9.2k', 'IG 팔로워'],
          ['Around', '베스트 스튜디오 10'],
        ],
      },
      {
        id: 'loop-calendar', num: '05', y: '2025',
        category: 'personal', categoryLabel: '실험',
        client: 'Side Project',
        title: 'Loop Calendar',
        tagline: '반복 일정만을 위한 미니 캘린더 — 한 화면, 한 주.',
        tags: ['Mobile', 'Productivity'],
        thumbGrad: 'linear-gradient(135deg, #C8DBFF 0%, #D5C8FF 35%, #FFD3EC 70%, #C8F0E1 100%)',
        thumbAccent: '#7FA3E0',
        thumbLabel: 'Week 21 · Loop',
        role: 'Solo · 사이드 프로젝트', roleSub: '진행 중',
        did: [
          '주간 시간표를 7×24 그리드 한 장으로 압축, 캡쳐 가능한 카드 형태로 출력',
          '반복 패턴 입력을 3개 슬라이더(요일·시작·길이)로 단순화',
          'iCal 연동 + 위젯 3사이즈 디자인',
        ],
        outcome: [
          ['n=180', 'TestFlight 베타'],
          ['#4', 'Product Hunt'],
          ['iOS 18', '위젯 피처드'],
        ],
      },
    ],
  },
  en: {
    badge: 'Portfolio · 2026',
    status: 'available · q3',
    name: ['Park', 'Junghyeok'],
    lang: { kor: '한국어', en: 'English' },
    role: 'Independent product designer focused on finance, tools, and quiet interfaces. I like seeing things through in small teams.',
    heroMeta: ['Seoul · KST', 'Est. 2017', '47 shipped', 'booking q3'],
    sectionLabel: 'Work',
    sectionMeta: '01 — 05 · 2023 → 2025',
    autoLabel: 'flowing',
    pausedLabel: 'paused',
    nudge: 'Hover a card to pause. Click to open.',
    nudgeReduced: 'Use the arrows below to step through.',
    actions: { back: 'Back to index', visit: 'Visit site', prev: 'Prev', next: 'Next' },
    arrow: { l: '←', r: '→' },
    detail: {
      year: 'YEAR', role: 'ROLE', client: 'CLIENT',
      did: 'What I did',
      outcome: 'Outcome',
      tags: 'Tags',
      ofTotal: (i, n) => `${String(i).padStart(2,'0')} / ${String(n).padStart(2,'0')}`,
      keyboardHint: '← → to navigate · Esc to close',
    },
    footer: {
      l: '© Park Junghyeok · 2026',
      c: 'Set in Fredoka + Gowun Dodum · made with care',
      email: 'hello@junghyeok.kr',
      github: 'github.com/junghyeok',
    },
    toast: { lang: 'Language · English' },
    projects: [
      {
        id: 'calm-banking', num: '01', y: '2025',
        category: 'company', categoryLabel: 'Company',
        client: 'Lattice Bank',
        title: 'Calm Banking',
        tagline: 'Compressed the entire transfer flow into one calm screen.',
        tags: ['Mobile', 'Fintech', 'Lead'],
        thumbGrad: 'linear-gradient(135deg, #FFD3E2 0%, #FFE5C2 35%, #C8F0E1 70%, #C8DBFF 100%)',
        thumbAccent: '#FF7FAE',
        thumbLabel: 'Transfer Flow · v.02',
        role: 'Lead Product Designer · 7 months', roleSub: 'iOS · Android',
        did: [
          'Reduced the 5-step transfer flow to 3, introduced an undo pattern for mis-sent payments.',
          'Redesigned account & card surfaces into a single card UI, cutting 32 modules to 12.',
          'Shipped 5 new onboarding screens that made time-to-first-transfer measurable.',
        ],
        outcome: [
          ['−38%', 'D7 NEW USER CHURN'],
          ['22→9s', 'AVG TRANSFER TIME'],
          ['4.8★', 'APP STORE · 12.4K'],
        ],
        live: true,
      },
      {
        id: 'foundry-docs', num: '02', y: '2024',
        category: 'personal', categoryLabel: 'Personal',
        client: 'Open Source',
        title: 'Foundry Docs',
        tagline: 'A static-site kit that makes dev docs read like a magazine.',
        tags: ['Web', 'Tooling'],
        thumbGrad: 'linear-gradient(135deg, #D9F4E5 0%, #CFE9FF 35%, #E2D3FF 70%, #FFD7F0 100%)',
        thumbAccent: '#8EC8B2',
        thumbLabel: 'Docs · /api/v2',
        role: 'Solo · Design & Build', roleSub: '12 weeks',
        did: [
          'Re-mapped 5 levels of hierarchy onto a book model — body, footnote, margin.',
          'Designed a 12-column grid that aligns code blocks and prose on the same axis.',
          'Made search, nav, and dark-mode all reachable with one-handed shortcuts.',
        ],
        outcome: [
          ['2.1k', 'GITHUB STARS'],
          ['14', 'OSS ADOPTIONS'],
          ['4m 12s', 'AVG SESSION'],
        ],
      },
      {
        id: 'saebyul-reader', num: '03', y: '2024',
        category: 'student', categoryLabel: 'Thesis',
        client: 'SNU Visual Design',
        title: 'Saebyul Reader',
        tagline: 'A short-fiction reader for the early hours of the morning.',
        tags: ['Mobile', 'Reading'],
        thumbGrad: 'linear-gradient(135deg, #E5D5FF 0%, #FFD5EC 35%, #FFE3D5 70%, #FFF1C8 100%)',
        thumbAccent: '#B89BE0',
        thumbLabel: 'Read · 03:14 AM',
        role: 'Solo · UX/UI', roleSub: 'Thesis · 16 weeks',
        did: [
          'Built a Hangul body-text system that adjusts kerning and leading by time of day.',
          'Designed a sentence-pacer interaction that breaks prose at the breath line.',
          'Shipped an offline-first architecture with per-author collections.',
        ],
        outcome: [
          ['27m', 'AVG SESSION'],
          ['64%', 'REPEAT RATE'],
          ['SDF', 'ROOKIE AWARD'],
        ],
      },
      {
        id: 'studio-kettle', num: '04', y: '2023',
        category: 'client', categoryLabel: 'Client',
        client: 'Local Brewery',
        title: 'Studio Kettle',
        tagline: 'Seasonal labels and a reservation site for a neighbourhood brewery.',
        tags: ['Brand', 'Web'],
        thumbGrad: 'linear-gradient(135deg, #FFE9C2 0%, #FFD3D3 35%, #FFD3EC 70%, #E2D3FF 100%)',
        thumbAccent: '#F0A878',
        thumbLabel: 'Brew · SS_23',
        role: 'Lead Designer · 8 weeks', roleSub: 'Brand + Web',
        did: [
          'Built a modular label system that flexes across seasons on a single grid.',
          'Streamlined the weekday-only menu reservation into a 3-step flow.',
          'Designed a typography-first menu card system that works without photos.',
        ],
        outcome: [
          ['8 WK', 'BOOKED OUT'],
          ['600→9.2k', 'INSTAGRAM'],
          ['Top 10', 'AROUND MAGAZINE'],
        ],
      },
      {
        id: 'loop-calendar', num: '05', y: '2025',
        category: 'personal', categoryLabel: 'Experiment',
        client: 'Side Project',
        title: 'Loop Calendar',
        tagline: 'A mini calendar only for recurring events — one screen, one week.',
        tags: ['Mobile', 'Productivity'],
        thumbGrad: 'linear-gradient(135deg, #C8DBFF 0%, #D5C8FF 35%, #FFD3EC 70%, #C8F0E1 100%)',
        thumbAccent: '#7FA3E0',
        thumbLabel: 'Week 21 · Loop',
        role: 'Solo · Side project', roleSub: 'In progress',
        did: [
          'Compressed a weekly schedule into a 7×24 grid that exports as a single shareable card.',
          'Reduced recurrence input to 3 sliders: day, start, length.',
          'Designed iCal sync and three widget sizes.',
        ],
        outcome: [
          ['n=180', 'TESTFLIGHT BETA'],
          ['#4', 'PRODUCT HUNT'],
          ['iOS 18', 'WIDGET FEATURED'],
        ],
      },
    ],
  },
};
